base_config: base.yaml
task: classification

data:
  preprocessing:
    clahe:
      enabled: true

model:
  backbone: tf_efficientnet_b4.ns_jft_in1k

train:
  epochs: 12
  loss:
    name: bce
    use_pos_weight: true

eval:
  threshold: 0.65